spring:
  application:
    name: ms-security
  profiles:
    active: dev
  datasource:
    url: "jdbc:mysql://dbcompany.cn48sgciaax1.us-east-2.rds.amazonaws.com:3306/dbcompany?useSSL=false&serverTimezone=UTC"
    username: desarrollador
    password: "Juliana1987****"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 5000
      idle-timeout: 300000
      max-lifetime: 600000
      keepalive-time: 60000
      connection-test-query: SELECT 1
      validation-timeout: 2000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
  show-actuator: false

security:
  jwt:
    secret: AF84F1FGllNpNnLG055fdg5hGHJK4KGG5VH5TR5J05JFGGDFDGXVV545J4505G666JFGF2mMY95y
  rol:
    todos:
      - ADMINISTRADOR
      - EMPRESA
      - OPERARIO
      - FONDEADOR
    carga:
      - ADMINISTRADOR
      - EMPRESA
      - OPERARIO
    revision:
      - ADMINISTRADOR
      - OPERARIO
      - FONDEADOR
    firma-subida:
      - ADMINISTRADOR
      - OPERARIO
    firma-guardado:
      - ADMINISTRADOR
      - EMPRESA