spring:
  datasource:
    url: "jdbc:mysql://dbcompany.cn48sgciaax1.us-east-2.rds.amazonaws.com:3306/dbcompany?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8"
    username: desarrollador
    password: "Juliana1987****"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: debug
    com.loadfilesservice: debug
    org.springframework.security: debug

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

security:
  jwt:
    secret: AF84F1FGllNpNnLG055fdg5hGHJK4KGG5VH5TR5J05JFGGDFDGXVV545J4505G666JFGF2mMY95y
  rol:
    todos:
      - ADMINISTRADOR
      - EMPRESA
      - OPERARIO
      - FONDEADOR
    carga:
      - ADMINISTRADOR
      - EMPRESA
      - OPERARIO
    revision:
      - ADMINISTRADOR
      - OPERARIO
      - FONDEADOR
    firma-subida:
      - ADMINISTRADOR
      - OPERARIO
    firma-guardado:
      - ADMINISTRADOR
      - EMPRESA