import com.tngtech.archunit.base.DescribedPredicate;
import com.tngtech.archunit.core.domain.JavaClass;
import com.tngtech.archunit.core.domain.JavaClasses;
import com.tngtech.archunit.core.importer.ClassFileImporter;
import com.tngtech.archunit.lang.ArchRule;
import org.junit.jupiter.api.Test;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;
import static com.tngtech.archunit.library.dependencies.SlicesRuleDefinition.slices;

public class ArchitectureTest {

    private static final DescribedPredicate<JavaClass> NOT_LOMBOK_GENERATED =
            DescribedPredicate.describe("not generated by Lombok",
                    javaClass -> !javaClass.isAnnotatedWith("lombok.Generated"));

    private final JavaClasses classes = new ClassFileImporter()
            .importPackages("com.loadfilesservice.loadfiles..")
            .that(NOT_LOMBOK_GENERATED);

    // ==================== REGLAS DE DEPENDENCIA ====================

    @Test
    void domain_no_debe_depende_de_nadie() {
        ArchRule rule = noClasses()
                .that().resideInAPackage("..domain..")
                .should().dependOnClassesThat()
                .resideInAnyPackage("..application..", "..infraestrutura..", "..web..");

        rule.check(classes);
    }

    @Test
    void application_solo_puede_depende_de_domain() {
        ArchRule rule = classes()
                .that().resideInAPackage("..application..")
                .should().onlyDependOnClassesThat()
                .resideInAnyPackage("..application..", "..domain..", "java..", "javax..", "jakarta..", "org.springframework..", "io.swagger.v3.oas..", "com.fasterxml.jackson..", "lombok..", "org.slf4j..");

        rule.check(classes);
    }

    @Test
    void infraestrutura_solo_puede_depende_de_application_y_domain() {
        ArchRule rule = classes()
                .that().resideInAPackage("..infraestrutura..")
                .should().onlyDependOnClassesThat()
                .resideInAnyPackage("..infraestrutura..", "..application..", "..domain..", "java..", "javax..", "jakarta..", "org.springframework..", "io.swagger.v3.oas..", "com.fasterxml.jackson..", "io.jsonwebtoken..", "lombok..", "org.slf4j..", "org.apache.kafka..", "org.apache.pdfbox..")
                .allowEmptyShould(true);

        rule.check(classes);
    }

    @Test
    void web_solo_puede_depende_de_application() {
        ArchRule rule = classes()
                .that().resideInAPackage("..web..")
                .should().onlyDependOnClassesThat()
                .resideInAnyPackage("..web..", "..application..", "..domain..", "java..", "jakarta..", "org.springframework..", "io.swagger.v3.oas..", "com.fasterxml.jackson..", "lombok..", "org.slf4j..");

        rule.check(classes);
    }

    // ==================== REGLAS DE NOMBRES Y ESTRUCTURA ====================

    @Test
    void controllers_deben_estar_en_web() {
        classes().that().haveNameMatching(".*Controller")
                .should().resideInAPackage("..web.controller..")
                .check(classes);
    }

    @Test
    void services_deben_estar_en_aplication_o_domain() {
        classes().that().haveNameMatching(".*Service")
                .should().resideInAnyPackage("..application.service..", "..domain..")
                .check(classes);
    }

    // ==================== REGLAS DE NO CICLOS Y ACOPLAMIENTO ====================

    @Test
    void no_deberia_haber_ciclos_entre_capas() {
        slices().matching("com.loadfilesservice.loadfiles.(*)..")
                .should().beFreeOfCycles()
                .check(classes);
    }

    @Test
    void domain_no_debe_usar_anotaciones_de_spring() {
        noClasses()
                .that().resideInAPackage("..domain..")
                .should().dependOnClassesThat()
                .haveNameMatching(".*(Spring|Autowired|Service|Repository|Controller).*")
                .check(classes);
    }
}